name:                lear
version:             0.1.0.0
github:              "jkarni/lear"
license:             BSD3
author:              "Julian K. Arni"
maintainer:          "jkarni@riseup.net"
copyright:           "2020 Julian K. Arni"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/lear#readme>

dependencies:
- base >= 4.7 && < 5
- adjunctions
- distributive
- recursion-schemes
- vector-space
- lens
- mtl
- ghc-typelits-natnormalise
- generic-lens

library:
  source-dirs: src

tests:
  lear-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lear
    - backprop
    - hspec
    - hspec-hedgehog
    - hedgehog >= 1.0.2
    - QuickCheck

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- MultiParamTypeClasses
- QuantifiedConstraints
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
- DefaultSignatures
- TypeApplications
- PolyKinds
