name:                lear-ad
version:             0.1.0.0
github:              "jkarni/lear"
license:             BSD3
author:              "Julian K. Arni"
maintainer:          "jkarni@riseup.net"
copyright:           "2020 Julian K. Arni"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/jkarni/lear#readme>

dependencies:
- base >= 4.7 && < 5
- lear
- backprop

library:
  source-dirs: src

tests:
  lear-backprop-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lear-backprop

default-extensions:
- RankNTypes
- FlexibleContexts
